from PyQt6 import QtCore, QtGui, QtWidgets
from gui_class import UploadWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 767)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 171, 721))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.leftbottom_frame = QtWidgets.QFrame(parent=self.frame_3)
        self.leftbottom_frame.setGeometry(QtCore.QRect(10, 430, 151, 281))
        self.leftbottom_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.leftbottom_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.leftbottom_frame.setLineWidth(1)
        self.leftbottom_frame.setMidLineWidth(1)
        self.leftbottom_frame.setObjectName("leftbottom_frame")
        self.checkbox_frame = QtWidgets.QFrame(parent=self.frame_3)
        self.checkbox_frame.setGeometry(QtCore.QRect(10, 180, 151, 241))
        self.checkbox_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.checkbox_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.checkbox_frame.setLineWidth(1)
        self.checkbox_frame.setMidLineWidth(1)
        self.checkbox_frame.setObjectName("checkbox_frame")
        self.status_frame = QtWidgets.QFrame(parent=self.frame_3)
        self.status_frame.setGeometry(QtCore.QRect(10, 10, 151, 161))
        self.status_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.status_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.status_frame.setLineWidth(1)
        self.status_frame.setMidLineWidth(1)
        self.status_frame.setObjectName("status_frame")
        self.bottom_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.bottom_frame.setGeometry(QtCore.QRect(170, 440, 731, 281))
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.bottom_frame.setLineWidth(1)
        self.bottom_frame.setMidLineWidth(1)
        self.bottom_frame.setObjectName("bottom_frame")
        self.LR_frame = QtWidgets.QFrame(parent=self.bottom_frame)
        self.LR_frame.setGeometry(QtCore.QRect(10, 20, 711, 251))
        self.LR_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.LR_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.LR_frame.setLineWidth(1)
        self.LR_frame.setMidLineWidth(1)
        self.LR_frame.setObjectName("LR_frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.bottom_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 344, 18))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.right_bottom_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.right_bottom_frame.setGeometry(QtCore.QRect(900, 440, 181, 281))
        self.right_bottom_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.right_bottom_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.right_bottom_frame.setLineWidth(1)
        self.right_bottom_frame.setMidLineWidth(1)
        self.right_bottom_frame.setObjectName("right_bottom_frame")
        self.frame_8 = QtWidgets.QFrame(parent=self.right_bottom_frame)
        self.frame_8.setGeometry(QtCore.QRect(10, 590, 151, 121))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_8.setLineWidth(1)
        self.frame_8.setMidLineWidth(1)
        self.frame_8.setObjectName("frame_8")
        self.mid_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.mid_frame.setGeometry(QtCore.QRect(170, 0, 911, 431))
        self.mid_frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.mid_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.mid_frame.setLineWidth(1)
        self.mid_frame.setMidLineWidth(1)
        self.mid_frame.setObjectName("mid_frame")
        self.origin_image = QtWidgets.QFrame(parent=self.mid_frame)
        self.origin_image.setGeometry(QtCore.QRect(10, 10, 431, 411))
        self.origin_image.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.origin_image.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.origin_image.setLineWidth(1)
        self.origin_image.setMidLineWidth(1)
        self.origin_image.setObjectName("origin_image")
        self.create_image = QtWidgets.QFrame(parent=self.mid_frame)
        self.create_image.setGeometry(QtCore.QRect(460, 10, 441, 411))
        self.create_image.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.create_image.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.create_image.setLineWidth(1)
        self.create_image.setMidLineWidth(1)
        self.create_image.setObjectName("create_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOption = QtWidgets.QMenu(parent=self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuTool = QtWidgets.QMenu(parent=self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuServer = QtWidgets.QMenu(parent=self.menubar)
        self.menuServer.setObjectName("menuServer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionconnecting = QtGui.QAction(parent=MainWindow)
        self.actionconnecting.setObjectName("actionconnecting")
        self.actionUpload = QtGui.QAction(parent=MainWindow)
        self.actionUpload.setObjectName("actionUpload")
        self.menuFile.addAction(self.actionUpload)
        
        self.menuServer.addAction(self.actionconnecting)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuServer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # 업로드 창 
    def showUploadWindow(self):
        self.uploadWindow = UploadWindow()
        self.uploadWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.menuTool.setTitle(_translate("MainWindow", "Tool"))
        self.menuServer.setTitle(_translate("MainWindow", "Server"))
        self.actionconnecting.setText(_translate("MainWindow", "connecting"))
        self.actionUpload.setText(_translate("MainWindow", "Upload"))
        self.actionUpload.triggered.connect(self.showUploadWindow) # 업로드 버튼 눌렀을 떄 showUploadWindow 실행 
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
